export const REASON_CODES = [
  "CONTRACT_NOT_APPROVED",
  "CONTRACT_EXPIRED",
  "ACTION_MISMATCH",
  "CHANNEL_MISMATCH",
  "TARGET_MISMATCH",
  "RECIPIENT_NOT_ALLOWED",
  "RESOURCE_FINGERPRINT_MISMATCH",
  "COST_LIMIT_EXCEEDED",
  "MAX_RUNS_EXCEEDED",
  "REPLAY_DETECTED",
  "ALL_RULES_PASSED",
] as const;
